name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Setup Go 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build reservation-service
        run: go build ./reservation-service/cmd/api

      - name: Build loyalty-service
        run: go build ./loyalty-service/cmd/api

      - name: Build payment-service
        run: go build ./payment-service/cmd/api

      - name: Build gateway-service
        run: go build ./gateway-service/cmd/api

      - name: Run UNIT Tests reservation-service
        run: go test ./reservation-service/internal/reservation/repo_test

      - name: Run UNIT Tests loyalty-service
        run: go test ./loyalty-service/internal/loyalty/repo_test

      - name: Run UNIT Tests payment-service
        run: go test ./payment-service/internal/payment/repo_test

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v2
          SERVICE_NAME: loyalty-service
          PORT_NUMBER: 8050

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 3
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v